### ISSUE TITLE
Add unique_id's to entities 

### ISSUE THREAD

**Issue by johntdyer** [pnbruckner/ha-sun2#72] opened 2022-12-01 12:26 UTC
Entities should have a unique ID so they can be modified via the UI, currently they do not and you get the following

<img width="670" alt="image" src="https://user-images.githubusercontent.com/58234/205052424-eb865087-fa24-4048-92bf-8b382a07bf51.png">

**Comment by pnbruckner** [comment] 2022-12-01 15:02
What settings do you want to change via the UI that you can't via YAML?

**Comment by johntdyer** [comment] 2022-12-01 15:22
Icon's , name, might want to hide some entities or assign to groups

**Comment by pnbruckner** [comment] 2022-12-02 19:26
A couple of the entities this integration creates dynamically change their icon based on state, so you'd probably not want to override those via the UI settings, but sure, you might want to with others I suppose.

You can change the name of the elevation binary sensor via YAML, and you can use namespace for at least partially controlling the entity IDs (and hence, names) of the others. But I'll grant you, you can't change the names and entity IDs in the same way you could via the UI settings.

As far as hiding, I guess that depends on how you control your dashboard configuration.

FWIW, this integration (like most of my custom integrations) was created long ago, before most integrations used unique IDs. But I've been slowly working on bringing them more up to date. E.g., I just overhauled my composite tracker integration, which now has unique IDs. I'll add this one to my list. The real issue is going to be coming up with a scheme for creating IDs that are unique and reproducible based on the existing configuration options. For some types of entities, it's pretty obvious and straightforward. For this one, I'm not so sure.

**Comment by RafaelSchridi** [comment] 2022-12-21 18:01
I ran into this issues trying to set a prefix to all entities (ie. sensor.sun2_london_sunset) but keep the friendly name (London Sunset)

Would that be possible or is that also in line the other changes required?

**Comment by pnbruckner** [comment] 2022-12-21 19:04
@RafaelSchridi would `sensor.london_sunset` with a friendly name of "London Sunset" work for you? That's exactly the example provided here: https://github.com/pnbruckner/ha-sun2#entity-namespace. Do you really need `sun2_` in the entity ID?

**Comment by RafaelSchridi** [comment] 2022-12-21 19:08
That's what I currently have, I just wanted a way to search all the entities in the integration.

**Comment by pnbruckner** [comment] 2022-12-21 20:03
@RafaelSchridi ok, thanks.

Well, given what I said above about it being difficult to come up with a way to determine a unique ID strictly based on the current configuration settings, I think the only reasonable way forward might be to add a `unique_id` optional configuration item. That way, anyone that cares can manage the unique IDs themselves. I've seen other integrations do this. Still, that might mean having to add it for every `monitored_conditions` entry, etc.

I'll have to think about this some more.

**Comment by pnbruckner** [comment] 2022-12-21 20:33
So here is what I'm thinking...

The unique ID can be the Entity Namespace + the name (as defined by the config.) Those just need to be unique for each type of Sun2 entity (i.e., `sensor` or `binary_sensor`) within a given system.

So, e.g., the unique IDs for "London" example would be "London Sunrise", "London Sunset", etc. Those _should_ actually be unique, and if not, then the user's config is probably nonoptimal anyway. And it _should_ work for `binary_sensor` entities, too.

I could try implementing something like that and then releasing a beta for people to try to see if there's anything I obviously overlooked. I'll put this back on my "to do" list.

**Comment by RafaelSchridi** [comment] 2022-12-21 21:26
I think the whole switching over to "unique ids" ideas what to catch problems with integrations that spit out multiple devices that are identical (ie. hue with 2 lights would be light.hue_light x2) But that doesn't look like that should be a problem here since all the entities are uniquely defined and there can't be duplicates. So you can arbitrarily define anything as "unique" probably and get away with it.
It looks like tere have been talks to use entity_namespace here but there have been no updates on that in 3 years (https://github.com/home-assistant/architecture/issues/333)

**Comment by pnbruckner** [comment] 2022-12-21 22:01
I did a quick test implementing what I mentioned above, and at the 30,000 ft level, it appears to "work." I.e., the entities show up on the Entities page, and you can override the entity IDs, names, etc. I'll need to do a bunch more testing to make sure there wasn't anything I overlooked, seeing as I haven't touched this code in quite some time. And along those same lines, it's probably due for some serious updating to take advantage of new infrastructure. I'll probably create a PR and commit the simple changes in case anyone wants to try it and provide feedback, as well as to remind me to spend some more time on it.

**Comment by RafaelSchridi** [comment] 2022-12-21 22:02
I'd be happy to help test this.

**Comment by pnbruckner** [comment] 2022-12-21 22:12
@RafaelSchridi 

> I'd be happy to help test this.

If you know how to use a branch from this repo, I'd appreciate it!

**Comment by pnbruckner** [comment] 2022-12-30 18:29
FYI, this is my current approach (and implementation, which I have not yet committed):

The "base" name of a sensor is derived from the `monitored_condition`. E.g., `nautical_dawn` would result in a base name of "Nautical Dawn". The base name for a binary sensor can be configured directly.

The friendly name of either type of sensor will be the same as the base name if no `namespace` is specified. If a `namespace` is specified, then the name will be the namespace + the base name. So, if the namespace is "London Town", and the base name is "Nautical Dawn", then the friendly name will be "London Town Nautical Dawn".

The unique ID that's used behind the scenes will be the same as the friendly name.

The entity ID will be pretty much as before.

Those are all the initial values given to the entity registry. The actual entity ID and name can then be changed to whatever you want via the Entities page.

**Closed** 2023-01-09 16:15 UTC
Labels: enhancement
