### ISSUE TITLE
Sun2 elevation not tracking sun

### ISSUE THREAD

**Issue by SamuelCarson** [pnbruckner/ha-sun2#22] opened 2020-06-16 16:34 UTC
Really strange results last 24 hours!
![sun2_elevation](https://user-images.githubusercontent.com/61090251/84801558-55270b00-afcd-11ea-9b37-8fcb23befd0b.png)

Latest sun2 integration with min_elevation.
HA 0.111.1

**Comment by pnbruckner** [comment] 2020-06-16 21:14
Can you share your sun2 configuration?

**Comment by SamuelCarson** [comment] 2020-06-17 02:06
# Enhanced Sun Sensors
- platform: sun2
  monitored_conditions:
    # - solar_midnight
    # - astronomical_dawn
    # - nautical_dawn
    # - dawn
    # - sunrise
    # - solar_noon
    # - sunset
    # - dusk
    # - nautical_dusk
    # - astronomical_dusk
    # - daylight
    # - civil_daylight
    # - nautical_daylight
    # - astronomical_daylight
    # - night
    # - civil_night
    # - nautical_night
    # - astronomical_night
    - elevation
    - max_elevation

**Comment by pnbruckner** [comment] 2020-06-17 02:43
So I assume the graph is from the elevation sensor, yes?

I'll set up a test to run overnight and through tomorrow. I may need to know, however, what your longitude, latitude, elevation & timezone settings are in order to reproduce the problem. If you don't want to share that data here then you can private message me on the community forum (pnbruckner) or on discord (pnbruckner#7311).

**Comment by pnbruckner** [comment] 2020-06-17 03:24
I think I might have found the problem (or, at least, a problem.) In 0.111.x a `core_config_updated` event is fired at HA startup which did not happen before. The elevation sensor listens for this event and updates if the event happens (since it signals that the longitude, latitude, etc. may have changed.) Unfortunately I was not handling that scenario correctly for the elevation sensor. I'm working on a fix.

I'm not sure if this is the reason, or if so, the only reason, for what you saw, so there may still be another problem. I'll let you know when I fix the problem noted above so you can try and see if it solves your problem.

**Comment by pnbruckner** [comment] 2020-06-17 04:31
Apparently the same problem exists in the binary elevation sensor as well, which needs the same fix.

**Comment by pnbruckner** [comment] 2020-06-17 14:41
The fix has been released in version 1.8.1. Can you test to see if that fixes your issue?

**Comment by SamuelCarson** [comment] 2020-06-17 15:18
Installed. 24 hours required to verify fix.

**Comment by SteveDinn** [comment] 2020-06-18 01:05
Installing now. Hopefully, my porch lights can come on at night again!

**Comment by SamuelCarson** [comment] 2020-06-18 13:09
Fixed

**Closed** 2020-06-18 17:31 UTC
Labels: bug
